apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Windows\System32\kompose.exe convert -f docker-compose.yml
    kompose.version: 1.24.0 (7c629530)
  creationTimestamp: null
  labels:
    io.kompose.service: hive-metastore-postgresql
  name: hive-metastore-postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: hive-metastore-postgresql
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Windows\System32\kompose.exe convert -f docker-compose.yml
        kompose.version: 1.24.0 (7c629530)
      creationTimestamp: null
      labels:
        io.kompose.service: hive-metastore-postgresql
    spec:
      containers:
        - image: bde2020/hive-metastore-postgresql:2.3.0
          name: hive-metastore-postgresql
          resources: {}
      restartPolicy: Always
status: {}
