apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Windows\System32\kompose.exe convert -f docker-compose.yml
    kompose.version: 1.24.0 (7c629530)
  creationTimestamp: null
  labels:
    io.kompose.service: namenode
  name: namenode
spec:
  type: NodePort
  ports:
    - name: "9870"
      port: 9870
      #targetPort: 9870
    - name: "9010"
      port: 9010
      #targetPort: 9000
  selector:
    io.kompose.service: namenode

