apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Windows\System32\kompose.exe convert -f docker-compose.yml
    kompose.version: 1.24.0 (7c629530)
  labels:
    io.kompose.service: spark-master
  name: spark-master
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: spark-master
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Windows\System32\kompose.exe convert -f docker-compose.yml
        kompose.version: 1.24.0 (7c629530)
      labels:
        io.kompose.service: spark-master
    spec:
      containers:
        - env:
            - name: CORE_CONF_fs_defaultFS
              value: hdfs://namenode:9000
            - name: INIT_DAEMON_STEP
              value: setup_spark
            - name: SPARK_MASTER_PORT
              value: "7077"
            - name: SPARK_MASTER_WEBUI_PORT
              value: "8080"
          image: bde2020/spark-master:3.0.0-hadoop3.2
          name: spark-master
          ports:
            - containerPort: 8080
            - containerPort: 7077
      restartPolicy: Always
