apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Windows\System32\kompose.exe convert -f docker-compose.yml
    kompose.version: 1.24.0 (7c629530)
  creationTimestamp: null
  labels:
    io.kompose.service: spark-worker-2
  name: spark-worker-2
spec:
  ports:
    - name: "8082"
      port: 8082
      targetPort: 8081
  selector:
    io.kompose.service: spark-worker-2
