apiVersion: apps/v1
kind: Deployment
metadata:
  name: superset
  labels:
    app: superset
spec:
  replicas: 1
  selector:
    matchLabels:
      app: superset
  template:
    metadata:
      labels:
        app: superset
    spec:
      containers:
        - name: superset
          image: apache/superset
          ports:
            - containerPort: 8088
          env:
            - name: SUPERSET_PORT
              value: "8088"
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: superset-secret
                  key: SECRET_KEY
