apiVersion: apps/v1
kind: Deployment
metadata:
  name: superset
  labels:
    app: superset
spec:
  replicas: 1
  selector:
    matchLabels:
      app: superset
  template:
    metadata:
      labels:
        app: superset
    spec:
      containers:
        - name: superset
          image: apache/superset
          ports:
            - containerPort: 8088
          env:
            - name: SUPERSET_PORT
              value: "8088"
            - name: SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  name: env
                  key: SUPERSET_SECRET_KEY
            - name: FLASK_ENV
              value: "development"  # Changez en "production" dans un environnement de production
            - name: PYTHONUNBUFFERED
              value: "0"
          command: ["gunicorn"]
          args: ["-w", "4", "-k", "gthread", "--timeout", "120", "-b", "0.0.0.0:8088", "superset.app:create_app()"]
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1"
          volumeMounts:
            - mountPath: /home/superset
              name: superset-data
      volumes:
        - name: superset-data
          persistentVolumeClaim:
            claimName: superset-pvc
